mkdir HG38
cd HG38
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr1.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr2.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr3.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr4.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr5.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr6.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr7.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr8.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr9.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr10.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr11.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr12.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr13.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr14.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr15.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr16.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr17.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr18.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr19.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr20.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr21.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr22.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chrM.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chrX.fa.gz"
curl -LJO "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chrY.fa.gz"
